import type { Drive, Car, Club, Route, User } from '@/types'

export const mockUser: User = {
  id: 'user-1',
  name: 'James Mitchell',
  initials: 'JM',
  location: 'New York, NY',
  memberSince: '2023',
  totalDrives: 24,
  totalMiles: 1847,
  clubs: ['amoc', 'grenadier'],
  cars: [
    {
      id: 'car-1',
      make: 'Aston Martin',
      model: 'DB11',
      year: 2021,
      color: 'Midnight Blue',
      colorHex: '#1a1a3a',
      spec: 'AMR spec · Tan leather',
      club: 'AMOC',
      clubBadge: 'verified',
      isPrimary: true,
      drives: 18,
      miles: 1240,
    },
    {
      id: 'car-2',
      make: 'INEOS',
      model: 'Grenadier',
      year: 2023,
      color: 'Cavalry Green',
      colorHex: '#2a4a1a',
      spec: 'Trialmaster spec',
      club: 'Grenadier Club',
      clubBadge: 'verified',
      isPrimary: false,
      drives: 6,
      miles: 607,
    },
    {
      id: 'car-3',
      make: 'Porsche',
      model: '911 GTS',
      year: 2019,
      color: 'Guards Red',
      colorHex: '#8a1a1a',
      club: 'PCA',
      clubBadge: 'self-declared',
      isPrimary: false,
      drives: 0,
      miles: 0,
    },
  ],
}

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Litchfield Hills Loop',
    description: 'A classic Connecticut run through rolling hills and charming villages.',
    states: ['CT'],
    miles: 67,
    durationMinutes: 100,
    character: ['spirited', 'scenic'],
    rating: 4.9,
    driveCount: 38,
    coordinates: [[-73.4, 41.7], [-73.5, 41.9], [-73.2, 42.0], [-73.0, 41.8], [-73.4, 41.7]],
  },
  {
    id: 'route-2',
    name: 'Taconic Ridge & Valley',
    description: 'The Taconic Parkway at its best — fast, flowing, and spectacular.',
    states: ['NY'],
    miles: 94,
    durationMinutes: 130,
    character: ['spirited'],
    rating: 4.7,
    driveCount: 24,
    coordinates: [[-73.7, 41.5], [-73.8, 41.8], [-73.6, 42.1], [-73.4, 42.3]],
  },
  {
    id: 'route-3',
    name: 'Route 100, Vermont',
    description: 'The spine of Vermont — Route 100 in full fall glory.',
    states: ['VT'],
    miles: 120,
    durationMinutes: 165,
    character: ['scenic', 'leisurely'],
    rating: 4.8,
    driveCount: 19,
    coordinates: [[-72.9, 43.0], [-72.8, 43.3], [-72.7, 43.6], [-72.6, 43.9]],
  },
  {
    id: 'route-4',
    name: 'Berkshire Back Roads',
    description: 'A new community route through the heart of the Berkshires.',
    states: ['MA'],
    miles: 112,
    durationMinutes: 165,
    character: ['scenic', 'spirited'],
    rating: 0,
    driveCount: 0,
    coordinates: [[-73.2, 42.3], [-73.1, 42.5], [-72.9, 42.7], [-72.8, 42.4]],
  },
]

export const mockDrives: Drive[] = [
  {
    id: 'drive-1',
    title: 'Hudson Valley Breakfast Run',
    type: 'destination',
    character: 'breakfast',
    visibility: 'open',
    date: '2025-06-07',
    departTime: '9:00 AM',
    meetingPoint: 'White Flower Farm, Litchfield CT',
    destination: 'The Inn at Pound Ridge',
    route: mockRoutes[0],
    states: ['CT', 'NY'],
    club: 'AMOC',
    organizerId: 'user-2',
    organizer: { name: 'Tom Keller', initials: 'TK' },
    maxSpots: 12,
    description: 'A classic Saturday morning run through Litchfield Hills to one of the best breakfast spots in the region. All cars welcome.',
    attendees: [
      { userId: 'u2', name: 'Tom Keller', initials: 'TK', avatarColor: '#1a3a2a', car: 'DB12', carColor: 'Aston Green', club: 'AMOC', status: 'going' },
      { userId: 'u3', name: 'Alex Whitmore', initials: 'AW', avatarColor: '#3a2a1a', car: 'Vantage', carColor: 'Silver', club: 'AMOC', status: 'going' },
      { userId: 'u4', name: 'Jane Park', initials: 'JP', avatarColor: '#1a2a3a', car: 'DBX', carColor: 'Onyx Black', club: 'AMOC', status: 'going' },
      { userId: 'u5', name: 'Marcus Reed', initials: 'MR', avatarColor: '#2a1a3a', car: 'DBS', carColor: 'Midnight Blue', club: 'AMOC', status: 'maybe', note: 'Might be a few minutes late!' },
      { userId: 'u6', name: 'Sarah Liu', initials: 'SL', avatarColor: '#1a2a1a', car: '911 Carrera', carColor: 'GT Silver', club: 'PCA', status: 'going' },
      { userId: 'u7', name: 'Chris Day', initials: 'CD', avatarColor: '#2a2a1a', car: 'AMG GT', carColor: 'Obsidian Black', status: 'going' },
    ],
  },
  {
    id: 'drive-2',
    title: 'VT–NY Equidistant Rally',
    type: 'equidistant',
    character: 'scenic',
    visibility: 'private',
    date: '2025-06-08',
    departTime: '10:00 AM',
    meetingPoint: 'Equidistant point: Manchester, VT',
    states: ['VT', 'NY'],
    organizerId: 'user-1',
    organizer: { name: 'James Mitchell', initials: 'JM' },
    attendees: [
      { userId: 'u1', name: 'James Mitchell', initials: 'JM', avatarColor: '#1e1a0e', car: 'DB11', carColor: 'Midnight Blue', club: 'AMOC', status: 'going' },
      { userId: 'u8', name: 'Steven Lang', initials: 'SL', avatarColor: '#1a1a2a', car: 'F8 Spider', carColor: 'Rosso', club: 'Ferrari Club', status: 'going' },
    ],
  },
  {
    id: 'drive-3',
    title: 'Taconic Sunday Spirited Run',
    type: 'loop',
    character: 'spirited',
    visibility: 'open',
    date: '2025-06-14',
    departTime: '8:30 AM',
    meetingPoint: 'Bedford Village, NY',
    route: mockRoutes[1],
    states: ['NY'],
    organizerId: 'user-9',
    organizer: { name: 'Rachel Kim', initials: 'RK' },
    maxSpots: 8,
    attendees: [
      { userId: 'u9', name: 'Rachel Kim', initials: 'RK', avatarColor: '#2a1a2a', car: 'M4 Competition', carColor: 'Brooklyn Grey', status: 'going' },
      { userId: 'u10', name: 'David Stone', initials: 'DS', avatarColor: '#1a2a2a', car: 'Cayman GT4', carColor: 'Miami Blue', club: 'PCA', status: 'going' },
    ],
  },
]

export const mockClubs: Club[] = [
  {
    slug: 'amoc',
    name: 'AMOC',
    fullName: 'Aston Martin Owners Club',
    make: 'Aston Martin',
    accentColor: '#c080e0',
    accentBg: '#1a1028',
    memberCount: 142,
    monthlyDrives: 8,
    icon: 'crown',
    verified: true,
  },
  {
    slug: 'grenadier',
    name: 'Grenadier Club',
    fullName: 'INEOS Grenadier Owners',
    make: 'INEOS Grenadier',
    accentColor: '#5B9CF6',
    accentBg: '#0f1e2a',
    memberCount: 67,
    monthlyDrives: 3,
    icon: 'mountain',
    verified: true,
  },
  {
    slug: 'pca',
    name: 'PCA',
    fullName: 'Porsche Club of America',
    make: 'Porsche',
    accentColor: '#C9A84C',
    accentBg: '#1a150a',
    memberCount: 318,
    monthlyDrives: 12,
    icon: 'circle-half',
    verified: false,
  },
  {
    slug: 'ferrari',
    name: 'Ferrari Club',
    fullName: 'Ferrari Owners of America',
    make: 'Ferrari',
    accentColor: '#E24B4A',
    accentBg: '#1a0a0a',
    memberCount: 203,
    monthlyDrives: 6,
    icon: 'horse-toy',
    verified: false,
  },
  {
    slug: 'defender',
    name: 'Defender Club',
    fullName: 'Land Rover Defender Owners',
    make: 'Land Rover Defender',
    accentColor: '#4CAF70',
    accentBg: '#0a1810',
    memberCount: 89,
    monthlyDrives: 4,
    icon: 'shield-chevron',
    verified: false,
  },
]

export const mockLeaderboard = [
  { rank: 1, name: 'Tom Keller', initials: 'TK', car: 'DB12 · Aston Green', miles: 2140, drives: 31, avatarColor: '#1a3a2a', textColor: '#60c090' },
  { rank: 2, name: 'Alex Whitmore', initials: 'AW', car: 'Vantage · Silver', miles: 1980, drives: 27, avatarColor: '#3a2a1a', textColor: '#d09060' },
  { rank: 3, name: 'Jane Park', initials: 'JP', car: 'DBX · Onyx Black', miles: 1870, drives: 25, avatarColor: '#1a2a3a', textColor: '#7090e0' },
  { rank: 4, name: 'James Mitchell', initials: 'JM', car: 'DB11 · Midnight Blue', miles: 1847, drives: 24, avatarColor: '#1e1a0e', textColor: '#C9A84C', isYou: true },
  { rank: 5, name: 'Marcus Reed', initials: 'MR', car: 'DBS · Midnight Blue', miles: 1620, drives: 21, avatarColor: '#2a1a3a', textColor: '#c080e0' },
]
